# Generated by Django 5.2.2 on 2025-11-12 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dusun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100, unique=True, verbose_name='Nama Dusun')),
                ('keterangan', models.TextField(blank=True, null=True, verbose_name='Keterangan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Dusun',
                'verbose_name_plural': 'Daftar Dusun',
                'ordering': ['nama'],
            },
        ),
        migrations.CreateModel(
            name='RW',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor', models.PositiveSmallIntegerField(verbose_name='Nomor RW')),
                ('ketua', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nama Ketua RW')),
                ('no_hp', models.CharField(blank=True, max_length=20, null=True, verbose_name='Nomor HP')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dusun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daftar_rw', to='admin_daerah.dusun', verbose_name='Dusun')),
            ],
            options={
                'verbose_name': 'RW',
                'verbose_name_plural': 'Daftar RW',
                'ordering': ['dusun', 'nomor'],
                'unique_together': {('dusun', 'nomor')},
            },
        ),
        migrations.CreateModel(
            name='RT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor', models.PositiveSmallIntegerField(verbose_name='Nomor RT')),
                ('ketua', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nama Ketua RT')),
                ('no_hp', models.CharField(blank=True, max_length=20, null=True, verbose_name='Nomor HP')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rw', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daftar_rt', to='admin_daerah.rw', verbose_name='RW')),
            ],
            options={
                'verbose_name': 'RT',
                'verbose_name_plural': 'Daftar RT',
                'ordering': ['rw__dusun', 'rw', 'nomor'],
                'unique_together': {('rw', 'nomor')},
            },
        ),
    ]
