# Generated by Django 5.2.2 on 2025-11-12 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_daerah', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rt',
            name='ketua',
        ),
        migrations.RemoveField(
            model_name='rt',
            name='no_hp',
        ),
        migrations.RemoveField(
            model_name='rw',
            name='ketua',
        ),
        migrations.RemoveField(
            model_name='rw',
            name='no_hp',
        ),
    ]
