# Generated by Django 5.2.2 on 2025-11-12 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnggotaKoperasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nik', models.CharField(max_length=16, unique=True)),
                ('nama_lengkap', models.CharField(max_length=200)),
                ('jenis_kelamin', models.CharField(choices=[('L', 'Laki-laki'), ('P', 'Perempuan')], max_length=1)),
                ('email', models.EmailField(max_length=254)),
                ('no_hp', models.CharField(max_length=20)),
                ('rt', models.CharField(max_length=5)),
                ('tanggal_daftar', models.DateTimeField(auto_now_add=True)),
                ('status_verifikasi', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified')], default='pending', max_length=10)),
            ],
        ),
    ]
